/*
 * LE Indexer API
 * &copy; 2018 Health Language
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EnrichmentOutput;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EnrichmentResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-01T09:30:57.014Z")
public class EnrichmentResponse {
  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("results")
  private List<EnrichmentOutput> results = null;

  public EnrichmentResponse requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * request id passed in, or generated UUID
   * @return requestId
  **/
  @ApiModelProperty(value = "request id passed in, or generated UUID")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public EnrichmentResponse results(List<EnrichmentOutput> results) {
    this.results = results;
    return this;
  }

  public EnrichmentResponse addResultsItem(EnrichmentOutput resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<EnrichmentOutput>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * list of result objects in the same order as the request texts.
   * @return results
  **/
  @ApiModelProperty(value = "list of result objects in the same order as the request texts.")
  public List<EnrichmentOutput> getResults() {
    return results;
  }

  public void setResults(List<EnrichmentOutput> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnrichmentResponse enrichmentResponse = (EnrichmentResponse) o;
    return Objects.equals(this.requestId, enrichmentResponse.requestId) &&
        Objects.equals(this.results, enrichmentResponse.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnrichmentResponse {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

