/*
 * LE Indexer API
 * &copy; 2018 Health Language
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EnrichmentInput;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EnrichmentRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-01T09:30:57.014Z")
public class EnrichmentRequest {
  @SerializedName("enrichmentInput")
  private List<EnrichmentInput> enrichmentInput = null;

  @SerializedName("requestId")
  private String requestId = null;

  public EnrichmentRequest enrichmentInput(List<EnrichmentInput> enrichmentInput) {
    this.enrichmentInput = enrichmentInput;
    return this;
  }

  public EnrichmentRequest addEnrichmentInputItem(EnrichmentInput enrichmentInputItem) {
    if (this.enrichmentInput == null) {
      this.enrichmentInput = new ArrayList<EnrichmentInput>();
    }
    this.enrichmentInput.add(enrichmentInputItem);
    return this;
  }

   /**
   * optional arbitrary ID for collating responses
   * @return enrichmentInput
  **/
  @ApiModelProperty(value = "optional arbitrary ID for collating responses")
  public List<EnrichmentInput> getEnrichmentInput() {
    return enrichmentInput;
  }

  public void setEnrichmentInput(List<EnrichmentInput> enrichmentInput) {
    this.enrichmentInput = enrichmentInput;
  }

  public EnrichmentRequest requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * optional arbitrary ID for collating responses
   * @return requestId
  **/
  @ApiModelProperty(value = "optional arbitrary ID for collating responses")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnrichmentRequest enrichmentRequest = (EnrichmentRequest) o;
    return Objects.equals(this.enrichmentInput, enrichmentRequest.enrichmentInput) &&
        Objects.equals(this.requestId, enrichmentRequest.requestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enrichmentInput, requestId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnrichmentRequest {\n");
    
    sb.append("    enrichmentInput: ").append(toIndentedString(enrichmentInput)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

