/*
 * LE Indexer API
 * &copy; 2018 Health Language
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EnrichmentRequest;
import io.swagger.client.model.UseCaseSupportedParameter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UseCase
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-01T09:30:57.014Z")
public class UseCase {
  @SerializedName("description")
  private String description = null;

  @SerializedName("exampleRequest")
  private EnrichmentRequest exampleRequest = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("supportedParameters")
  private List<UseCaseSupportedParameter> supportedParameters = null;

  public UseCase description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UseCase exampleRequest(EnrichmentRequest exampleRequest) {
    this.exampleRequest = exampleRequest;
    return this;
  }

   /**
   * Get exampleRequest
   * @return exampleRequest
  **/
  @ApiModelProperty(value = "")
  public EnrichmentRequest getExampleRequest() {
    return exampleRequest;
  }

  public void setExampleRequest(EnrichmentRequest exampleRequest) {
    this.exampleRequest = exampleRequest;
  }

  public UseCase id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UseCase supportedParameters(List<UseCaseSupportedParameter> supportedParameters) {
    this.supportedParameters = supportedParameters;
    return this;
  }

  public UseCase addSupportedParametersItem(UseCaseSupportedParameter supportedParametersItem) {
    if (this.supportedParameters == null) {
      this.supportedParameters = new ArrayList<UseCaseSupportedParameter>();
    }
    this.supportedParameters.add(supportedParametersItem);
    return this;
  }

   /**
   * parameters that apply to the use case
   * @return supportedParameters
  **/
  @ApiModelProperty(value = "parameters that apply to the use case")
  public List<UseCaseSupportedParameter> getSupportedParameters() {
    return supportedParameters;
  }

  public void setSupportedParameters(List<UseCaseSupportedParameter> supportedParameters) {
    this.supportedParameters = supportedParameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UseCase useCase = (UseCase) o;
    return Objects.equals(this.description, useCase.description) &&
        Objects.equals(this.exampleRequest, useCase.exampleRequest) &&
        Objects.equals(this.id, useCase.id) &&
        Objects.equals(this.supportedParameters, useCase.supportedParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, exampleRequest, id, supportedParameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UseCase {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    exampleRequest: ").append(toIndentedString(exampleRequest)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    supportedParameters: ").append(toIndentedString(supportedParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

