/*
 * LE Indexer API
 * &copy; 2018 Health Language
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import java.util.Arrays;

import org.junit.Test;
import org.junit.runner.RunWith;

import com.anarsoft.vmlens.concurrent.junit.ThreadCount;

import io.swagger.client.ApiException;
import io.swagger.client.model.EnrichmentInput;
import io.swagger.client.model.EnrichmentRequest;
import io.swagger.client.model.EnrichmentResponse;

/**
 * API tests for ContentEnrichmentApi
 */

@RunWith(com.anarsoft.vmlens.concurrent.junit.ConcurrentTestRunner.class)

public class ContentEnrichmentApiTest
{

    private final ContentEnrichmentApi api = new ContentEnrichmentApi();

    /**
     * Runs content enrichment for full text. Enriches full text content with code annotations. This
     * endpoint supports enrichment via pre-defined use cases. The supported parameters vary by use
     * case - use the /usecases endpoint to see the available options. &lt;br&gt; &lt;br&gt; Example
     * input: &lt;br&gt;
     * {&lt;br&gt;\&quot;enrichmentInput\&quot;:[{&lt;br&gt;\&quot;text\&quot;:\&quot;She is known
     * to have nonischemic
     * cardiomyopathy.\&quot;,&lt;br&gt;\&quot;useCaseId\&quot;:\&quot;snomed_indexer\&quot;,&lt;br&gt;\&quot;parameters\&quot;:{\&quot;codeGroups\&quot;:[\&quot;cd2177f2-d1d3-4e4f-9a60-7b88cc45c99c\&quot;,\&quot;d332aa64-2c79-45bc-baa1-d5aa4abdb2c9\&quot;]}&lt;br&gt;}]&lt;br&gt;}
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @ThreadCount(2)
    public void enrichUsingPOSTMultiThreadingTest() throws Exception
    {

        try
        {

            EnrichmentRequest request = new EnrichmentRequest().addEnrichmentInputItem(new EnrichmentInput().text(
                "Darrow DH, Greene AK, Mancini AJ, et al. Diagnosis and management of infantile hemangioma. Pediatrics. 2015;136:e1060-e1104.")
                            .useCaseId("snomed_indexer")
                            .putParametersItem("codeGroupIds", Arrays.asList("d3516463-826c-447c-8ed8-db9000484b1a")));
            EnrichmentResponse response = api.enrichUsingPOST(request);
            response.getResults().forEach(s -> System.out.println(s));
            
        }
        catch (Exception e)
        {
            e.printStackTrace();
            throw e;
        }
    }

}
